package bondhon.management.system;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */


    int id;
    public Dashboard(int id1) {
        initComponents();
        
        
        
        id=id1;
        
        try{
          String url = "jdbc:mysql://localhost:3306/bondhon";
        String dUser = "root";
        String dPass = "";

        try {
            Connection connection = DriverManager.getConnection(url, dUser, dPass);

            // Replace these with user-provided values
           

            // Create a prepared statement to check if the user's email and password match
            String sql = "SELECT id,name, email,image FROM bondhonuser WHERE id = ?";

            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, id1);

            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                String name = resultSet.getString("name");
                String email = resultSet.getString("email");
               txt_name.setText(name);
               txt_email.setText(email);
               
               byte[] imageData = resultSet.getBytes("image");
  
                // Convert the byte array into an Image
                ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(imageData);
                BufferedImage bufferedImage = ImageIO.read(byteArrayInputStream);
                //ImageIcon imageIcon = new ImageIcon(bufferedImage);
                int width = 115; // Set your desired width
                int height = 98; // Set your desired height

                // Resize the image
                Image resizedImage = bufferedImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(resizedImage);
                pic.setIcon(imageIcon);
            } else {
                // User with the provided email not found
                System.out.println("User with the provided email not found.");
                
            }

            
            
            
            // Close resources
            resultSet.close();
            preparedStatement.close();
            connection.close();
            
            
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
       /* 
        String imageurl="C:\\Users\\Acer\\Documents\\NetBeansProjects\\Bondhon Management System\\src\\icon/dash12.jpg";
        File imageFile = new File(imageurl);
         if (imageFile != null && imageFile.exists()) {
            ImageIcon imageIcon = new ImageIcon(imageFile.getAbsolutePath());
            Image image = imageIcon.getImage();
            Image scaledImage = image.getScaledInstance( 650, 1210, Image.SCALE_SMOOTH);
            btn_dashpic.setIcon(new ImageIcon(scaledImage));
        } else {
            btn_dashpic.setIcon(null);
        }*/
       
        
       
       
      // while(true){
           //text.setVisible(false);
           
      //}*/
       
     //add();  
       
       
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        btn_search = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_profilepic = new javax.swing.JButton();
        btn_logout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_news = new javax.swing.JButton();
        txt_name = new javax.swing.JLabel();
        txt_email = new javax.swing.JLabel();
        pic = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menu_search = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        combo_changepic = new javax.swing.JCheckBoxMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1672, 827));

        panel1.setBackground(new java.awt.Color(102, 102, 0));

        btn_search.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_view.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_view.setText("VIEW PROFILE");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_edit.setLabel("EDIT PROFILE");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_profilepic.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_profilepic.setText("CHANGE PROFILE PICTURE");
        btn_profilepic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profilepicActionPerformed(evt);
            }
        });

        btn_logout1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_logout1.setText("LOG OUT");
        btn_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logout1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dash12.jpg"))); // NOI18N

        btn_news.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_news.setText("NEWS PAPER");
        btn_news.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_profilepic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_logout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_news, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_profilepic, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_news, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        txt_name.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setText("jLabel4");

        txt_email.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setText("jLabel4");

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dash4.jpg"))); // NOI18N
        pic.setText("jButton1");
        pic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Find");

        menu_search.setText("SECARCH");
        menu_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_searchActionPerformed(evt);
            }
        });
        jMenu3.add(menu_search);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("View");

        jMenuItem2.setText("View Profile");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Edit");

        jMenuItem3.setText("Edit profile");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        combo_changepic.setSelected(true);
        combo_changepic.setText("EDIT PICTURE");
        combo_changepic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_changepicActionPerformed(evt);
            }
        });
        jMenu6.add(combo_changepic);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Settings");

        jMenuItem4.setText("Edit Profile");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText("Change Password");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        menu_logout.setText("Log Out");
        menu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_logoutActionPerformed(evt);
            }
        });
        jMenu7.add(menu_logout);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_profilepicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profilepicActionPerformed
        // TODO add your handling code here:
        
                        setVisible(false); 
                             Updateprofilepic changepicFrame=new Updateprofilepic(id);
                        //Updateprofilepic LoginFrame=new Updateprofilepic (int id);
                       changepicFrame.setVisible(true);
                     changepicFrame.pack();
                       changepicFrame.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_btn_profilepicActionPerformed

    private void menu_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_searchActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
       
                        Search searchFrame=new Search(id);
                        searchFrame.setVisible(true);
                        searchFrame.pack();
                        searchFrame.setLocationRelativeTo(null); 
        
    }//GEN-LAST:event_menu_searchActionPerformed

    private void menu_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_logoutActionPerformed
        // TODO add your handling code here:
                       setVisible(false); 
       
                        Login LoginFrame=new Login();
                        LoginFrame.setVisible(true);
                        LoginFrame.pack();
                        LoginFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_logoutActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
                    Search searchFrame=new Search(id);
                        searchFrame.setVisible(true);
                        searchFrame.pack();
                        searchFrame.setLocationRelativeTo(null); 
        
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
       
                        Viewprofile ViewFrame=new Viewprofile(id);
                        ViewFrame.setVisible(true);
                        ViewFrame.pack();
                        ViewFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_viewActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
                        Viewprofile ViewFrame=new Viewprofile(id);
                        ViewFrame.setVisible(true);
                        ViewFrame.pack();
                        ViewFrame.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
                        Editprofile EditFrame=new Editprofile(id);
                        EditFrame.setVisible(true);
                        EditFrame.pack();
                        EditFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
                        Editprofile EditFrame=new Editprofile(id);
                        EditFrame.setVisible(true);
                        EditFrame.pack();
                        EditFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
                        Editprofile EditFrame=new Editprofile(id);
                        EditFrame.setVisible(true);
                        EditFrame.pack();
                        EditFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_editActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        setVisible(false); 
                        Changepassword passFrame=new Changepassword(id);
                        passFrame.setVisible(true);
                        passFrame.pack();
                        passFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void picActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picActionPerformed
        // TODO add your handling code here:
        new Profilepic(id);
    }//GEN-LAST:event_picActionPerformed

    private void btn_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logout1ActionPerformed
        // TODO add your handling code here:
        
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            // Perform logout actions here
            JOptionPane.showMessageDialog(this, "Logout successful!");
                setVisible(false); 
       
                        Login LoginFrame=new Login();
                        LoginFrame.setVisible(true);
                        LoginFrame.pack();
                        LoginFrame.setLocationRelativeTo(null);
            // Add your logout logic here
        } else {
            // User chose not to logout
            JOptionPane.showMessageDialog(this, "Logout canceled.");
        }
                       
    }//GEN-LAST:event_btn_logout1ActionPerformed

    private void combo_changepicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_changepicActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
                        Updateprofilepic changepicFrame=new Updateprofilepic(id);
                        //Updateprofilepic LoginFrame=new Updateprofilepic (int id);
                       changepicFrame.setVisible(true);
                       changepicFrame.pack();
                       changepicFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_combo_changepicActionPerformed

    private void btn_newsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newsActionPerformed
        // TODO add your handling code here:
        setVisible(false); 
        NewsApp newsframe=new NewsApp(id);
        newsframe.setVisible(true);
        newsframe.pack();
        newsframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_newsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(12).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout1;
    private javax.swing.JButton btn_news;
    private javax.swing.JButton btn_profilepic;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_view;
    private javax.swing.JCheckBoxMenuItem combo_changepic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menu_logout;
    private javax.swing.JMenuItem menu_search;
    private java.awt.Panel panel1;
    private javax.swing.JButton pic;
    private javax.swing.JLabel txt_email;
    private javax.swing.JLabel txt_name;
    // End of variables declaration//GEN-END:variables
}
