package bondhon.management.system;
import java.io.File;
import java.io.FileInputStream; 
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Acer
 */
public class SignUp3 extends javax.swing.JFrame {
    User user=new User();
    File imageFile;// = new File(imageurl);
    /**
     * Creates new form SignUp3
     */
    public SignUp3(){
            initComponents();
                }
    public SignUp3(User user1) {
        user=user1;
        // System.out.println(user.getGender());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        combo_religion = new javax.swing.JComboBox<>();
        combo_nationality = new javax.swing.JComboBox<>();
        combo_education = new javax.swing.JComboBox<>();
        combo_marital = new javax.swing.JComboBox<>();
        combo_hobby = new javax.swing.JComboBox<>();
        combo_height = new javax.swing.JComboBox<>();
        txt_weight = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        combo_district = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1672, 827));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("PERSONAL INFORMATION");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HEIGHT");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WEIGHT");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADDRESS");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RELIGION");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NATIONALITY");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EDUCATIONAL STATUS");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MARITAL STATUS");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HOBBY");

        combo_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "HINDU", "BUDDHA", "CHRISTIAN" }));

        combo_nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANGLADESHI", "AMERICAN", "CANADIAN", "AUSTRALIAN", "FRENCH", "GERMAN", "JAPANESE", "ITALIAN", "SPANISH", "CHINESE", "BRAZILIAN", "INDIAN", "RUSSIAN", "MEXICAN", "BRITISH", "SWEDISH", " ", " " }));

        combo_education.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "PEC", "JSC", "SSC", "HSC", "BSC", "MSC", "PhD", " " }));

        combo_marital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE", "MARRIED", "DIVORCED", "WIDOWED", "SEPARATED", "ENGAGED" }));

        combo_hobby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READING", "WRITING", "PAINTING", "DRAWING", "SINGING", "DANCING", "COOKING", "GARDENING", "HIKING", "PHOTOGRAPHY", "TRAVELING", "PLAYING MUSICAL INSTRUMENTS (e.g., guitar, piano, violin)", "YOGA", "SWIMMING", "FISHING", "KNITTING OR CROCHETING", "BIRD-WATCHING", "MODEL BUILDING", "COLLECTING (e.g., stamps, coins, vintage items)", "VOLUNTEERING" }));

        combo_height.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        combo_height.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4'4''", "4'5''", "4'6''", "4'7''", "4'8''", "4'9''", "4'10''", "4'11''", "5'0''", "5'1''", "5'2''", "5'3''", "5'4''", "5'5''", "5'6''", "5'7''", "5'8''", "5'9''", "5'10''", " " }));

        btn_back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_next.setText("NEXT");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DISTRICT");

        combo_district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DHAKA", "CHITTAGONG", "KHULNA", "RAJSHAHI", "BARISAL", "SYLHET", "RANGPUR", "MYMENSINGH", "COMILLA", "NARAYANGANJ" }));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PROFILE PICTURE");

        jButton1.setText("choose file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(btn_back)
                        .addGap(53, 53, 53)
                        .addComponent(btn_next))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_marital, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_education, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_district, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_height, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(841, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_district, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(combo_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combo_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combo_education, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(combo_marital, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(combo_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(btn_next))
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1569, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
          setVisible(false); 
       
        SignUp2 SignUp2Frame=new SignUp2(user);
       SignUp2Frame.setVisible(true);
       SignUp2Frame.pack();
       SignUp2Frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        try {
        // Code that may throw an IOException
        String height=combo_height.getSelectedItem().toString();
        String weight=txt_weight.getText();
        if(weight.equals(""))
        {
             JOptionPane.showMessageDialog(new JFrame(), "ENTER CURRECT WEIGHT!!", "Eroor", JOptionPane.ERROR_MESSAGE);    
            return; 
        }
        String address=txt_address.getText().toUpperCase();
        if(address.length()<3)
        {
             JOptionPane.showMessageDialog(new JFrame(), "ENTER CURRECT ADDRESS!!", "Eroor", JOptionPane.ERROR_MESSAGE);    
            return; 
        }
        String religion=combo_religion.getSelectedItem().toString();
        String nationality=combo_nationality.getSelectedItem().toString();
        String education=combo_education.getSelectedItem().toString();
        String marital=combo_marital.getSelectedItem().toString();
        String hobby=combo_hobby.getSelectedItem().toString();
        String district=combo_district.getSelectedItem().toString();
        
        String email=user.getEmail();
        String password=user.getPassword();
        String name=user.getName();
        String fatherName=user.getFatherName();
        String motherName=user.getMotherName();
        String birthday=user.getBirthday();
        String gender=user.getGender();
        String age=Integer.toString(user.getAge());
        String mobileNumber=user.getMobileNumber();
        
       /* String imageurl="C:\\Users\\Acer\\Documents\\NetBeansProjects\\Bondhon Management System\\src\\icon/dash4.jpg";
        
        if(!"".equals(txt_image.getText()))
        {
            imageurl=txt_image.getText();
        }
        */
        if (!(imageFile != null && imageFile.exists())){
          JOptionPane.showMessageDialog(new JFrame(), "UPLOAD PROFILE PICTURE!!", "Eroor", JOptionPane.ERROR_MESSAGE);    
            return;  
            
        }
       
        String url = "jdbc:mysql://localhost:3306/bondhon";
        String duser = "root";
        String dpassword = ""; // Replace with your actual password
       
        try (Connection connection = DriverManager.getConnection(url, duser, dpassword)) {
            if (connection != null) {
                
                //System.out.println("Connected to the MySQL database!");
                 //File imageFile = new File(imageurl);
                FileInputStream fis = new FileInputStream(imageFile);
                 // Define the SQL query with placeholders
                String insertQuery = "INSERT INTO  bondhonuser ( name, fathername , mothername , birthday , mobile , email , password ,district , address , height , weight , age , religion , nationality , gender , education , maritalstatus , hobby ,image) VALUES (?, ? ,?, ? , ?, ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?,?)";

                // Create a PreparedStatement
                try (PreparedStatement preparedStatement = connection.prepareStatement(insertQuery)) {
                    // Set the values for the placeholders
                    
                    preparedStatement.setString(1, name);   
                    preparedStatement.setString(2, fatherName);
                    preparedStatement.setString(3, motherName);    
                    preparedStatement.setString(4, birthday);
                    
                    
                    preparedStatement.setString(5, mobileNumber);    //SET TO INSRTION
                    preparedStatement.setString(6, email);
                    preparedStatement.setString(7, password);
                    // Replace with the actual address
                    preparedStatement.setString(8, district);
                    preparedStatement.setString(9, address);
                    
                    preparedStatement.setString(10, height);    
                    preparedStatement.setString(11, weight);
                    preparedStatement.setString(12, age);    
                    preparedStatement.setString(13, religion);
                    
                    preparedStatement.setString(14, nationality);    
                    preparedStatement.setString(15, gender);
                    preparedStatement.setString(16, education);    
                    preparedStatement.setString(17, marital);
                    
                    preparedStatement.setString(18, hobby);
                   // preparedStatement.setBinaryStream(19, fis, (int) imageFile.length());
                     preparedStatement.setBlob(19, fis); 
                    // Replace with the actual room count

                    // Execute the INSERT statement
                    int rowsAffected = preparedStatement.executeUpdate();

                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(new JFrame(), "INSERTION SUCESSFULL!!", "SUCCESS", JOptionPane.ERROR_MESSAGE);    
                       // System.out.println("Insertion successful. " + rowsAffected + " row(s) affected.");
                        
                         fis.close();
                        preparedStatement.close();
                        connection.close();
                        setVisible(false); 
       
                        Login LoginFrame=new Login();
                        LoginFrame.setVisible(true);
                        LoginFrame.pack();
                        LoginFrame.setLocationRelativeTo(null);
                        
                    } else {
                        //System.out.println("Insertion failed.");
                        JOptionPane.showMessageDialog(new JFrame(), "INSERTION FAILED!!", "Eroor", JOptionPane.ERROR_MESSAGE);    
                    }
                } catch (SQLException e) {
                    //System.err.println("Error executing the PreparedStatement: " + e.getMessage());
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(new JFrame(), "INSERTION FAILED!!\nCHECK ERROR.", "Eroor", JOptionPane.ERROR_MESSAGE);    
                }
                
                // You can now use the 'connection' object to interact with the database
                // For example, you can create and execute SQL queries here.
            } else {
                //System.out.println("Failed to connect to the database.");
                JOptionPane.showMessageDialog(new JFrame(), "Failed to connect to the database.", "Eroor", JOptionPane.ERROR_MESSAGE);    
            }
        } catch (SQLException e) {
            //System.err.println("Error connecting to the database: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(new JFrame(), "Error connecting to the database:", "Eroor", JOptionPane.ERROR_MESSAGE);    
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignUp3.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    
    } catch (IOException e) {
        // Handle the exception
        
    }   
        
       
    }//GEN-LAST:event_btn_nextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif", "bmp");
                fileChooser.setFileFilter(filter);

                int returnValue = fileChooser.showOpenDialog(null);

                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    //File selectedFile = fileChooser.getSelectedFile();
                    imageFile=fileChooser.getSelectedFile();
                    //storeImageInDatabase(selectedFile);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_next;
    private javax.swing.JComboBox<String> combo_district;
    private javax.swing.JComboBox<String> combo_education;
    private javax.swing.JComboBox<String> combo_height;
    private javax.swing.JComboBox<String> combo_hobby;
    private javax.swing.JComboBox<String> combo_marital;
    private javax.swing.JComboBox<String> combo_nationality;
    private javax.swing.JComboBox<String> combo_religion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
