 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bondhon.management.system;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Acer
 */
public class Updateprofilepic extends javax.swing.JFrame {

    /**
     * Creates new form Updateprofilepic
     */
    int id;
    File imageFile;
    public Updateprofilepic(int id1) {
        id=id1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selsetfile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_upload = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("CHANGE PROFILE PICTURE");

        selsetfile.setText("CHOOSE FILE");
        selsetfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selsetfileActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROFILE PICTURE ");

        btn_back.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_upload.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_upload.setText("UPLOAD");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(selsetfile, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btn_back)
                        .addGap(125, 125, 125)
                        .addComponent(btn_upload)))
                .addContainerGap(1028, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selsetfile))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(btn_upload))
                .addContainerGap(584, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
                        setVisible(false); 
                        Dashboard dashFrame=new Dashboard(id);
                        dashFrame.setVisible(true);
                        dashFrame.pack();
                        dashFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_backActionPerformed

    private void selsetfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selsetfileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif", "bmp");
                fileChooser.setFileFilter(filter);

                int returnValue = fileChooser.showOpenDialog(null);

                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    //File selectedFile = fileChooser.getSelectedFile();
                    imageFile=fileChooser.getSelectedFile();
                    //storeImageInDatabase(selectedFile);
                }
    }//GEN-LAST:event_selsetfileActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        
         try {
        // Code that may throw an IOException
        
        
        
       /* String imageurl="C:\\Users\\Acer\\Documents\\NetBeansProjects\\Bondhon Management System\\src\\icon/dash4.jpg";
        
        if(!"".equals(txt_image.getText()))
        {
            imageurl=txt_image.getText();
        }
        */
        if (!(imageFile != null && imageFile.exists())){
          JOptionPane.showMessageDialog(new JFrame(), "UPLOAD CURRECT PROFILE PICTURE!!", "Eroor", JOptionPane.ERROR_MESSAGE);    
            return;  
            
        }
       
        String url = "jdbc:mysql://localhost:3306/bondhon";
        String duser = "root";
        String dpassword = ""; // Replace with your actual password
       
        try (Connection connection = DriverManager.getConnection(url, duser, dpassword)) {
            if (connection != null) {
                
                System.out.println("Connected to the MySQL database!");
                 //File imageFile = new File(imageurl);
                FileInputStream fis = new FileInputStream(imageFile);
                 // Define the SQL query with placeholders
                String insertQuery = "UPDATE bondhonuser SET image = ? where id = ? "; 

                // Create a PreparedStatement
                try (PreparedStatement preparedStatement = connection.prepareStatement(insertQuery)) {
                    // Set the values for the placeholders
                    
                    
                   // preparedStatement.setBinaryStream(19, fis, (int) imageFile.length());
                     preparedStatement.setBlob(1, fis); 
                     preparedStatement.setInt(2,id);
                    // Replace with the actual room count

                    // Execute the INSERT statement
                    int rowsAffected = preparedStatement.executeUpdate();

                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(new JFrame(), "INSERTION SUCESSFULL!!", "Eroor", JOptionPane.ERROR_MESSAGE);    
                        System.out.println("Insertion successful. " + rowsAffected + " row(s) affected.");
                        
                         fis.close();
                        preparedStatement.close();
                        connection.close();
                        setVisible(false); 
       
                        setVisible(false); 
                        Dashboard dashFrame=new Dashboard(id);
                        dashFrame.setVisible(true);
                        dashFrame.pack();
                        dashFrame.setLocationRelativeTo(null);
                    } else {
                        System.out.println("Insertion failed.");
                        JOptionPane.showMessageDialog(new JFrame(), "INSERTION FAILED!!", "Eroor", JOptionPane.ERROR_MESSAGE);    
                    }
                } catch (SQLException e) {
                    System.err.println("Error executing the PreparedStatement: " + e.getMessage());
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(new JFrame(), "INSERTION FAILED!!\nCHECK ERROR.", "Eroor", JOptionPane.ERROR_MESSAGE);    
                }
                
                // You can now use the 'connection' object to interact with the database
                // For example, you can create and execute SQL queries here.
            } else {
                System.out.println("Failed to connect to the database.");
                JOptionPane.showMessageDialog(new JFrame(), "Failed to connect to the database.", "Eroor", JOptionPane.ERROR_MESSAGE);    
            }
        } catch (SQLException e) {
            System.err.println("Error connecting to the database: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(new JFrame(), "Error connecting to the database:", "Eroor", JOptionPane.ERROR_MESSAGE);    
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignUp3.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    
    } catch (IOException e) {
        // Handle the exception
        
    }   
    }//GEN-LAST:event_btn_uploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateprofilepic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateprofilepic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateprofilepic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateprofilepic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateprofilepic(12).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_upload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton selsetfile;
    // End of variables declaration//GEN-END:variables
}
